exports.comp = [
  'DRUG_CODE',
  'MFR_CODE',
  'COMPANY_CODE',
  'COMPANY_NAME',
  'COMPANY_TYPE',
  'ADDRESS_MAILING_FLAG',
  'ADDRESS_BILLING_FLAG',
  'ADDRESS_NOTIFICATION_FLAG',
  'ADDRESS_OTHER',
  'SUITE_NUMBER',
  'STREET_NAME',
  'CITY_NAME',
  'PROVINCE',
  'COUNTRY',
  'POSTAL_CODE',
  'POST_OFFICE_BOX',
  'PROVINCE_F',
  'COUNTRY_F',
];

exports.ingred = [
  'DRUG_CODE',
  'ACTIVE_INGREDIENT_CODE',
  'INGREDIENT',
  'INGREDIENT_SUPPLIED_IND',
  'STRENGTH',
  'STRENGTH_UNIT',
  'STRENGTH_TYPE',
  'DOSAGE_VALUE',
  'BASE',
  'DOSAGE_UNIT',
  'NOTES',
  'INGREDIENT_F',
  'STRENGTH_UNIT_F',
  'STRENGTH_TYPE_F',
  'DOSAGE_UNIT_F',
];

exports.drug = [
  'DRUG_CODE',
  'PRODUCT_CATEGORIZATION',
  'CLASS',
  'DRUG_IDENTIFICATION_NUMBER',
  'BRAND_NAME',
  'DESCRIPTOR',
  'PEDIATRIC_FLAG',
  'ACCESSION_NUMBER',
  'NUMBER_OF_AIS',
  'LAST_UPDATE_DATE',
  'AI_GROUP_NO',
  'CLASS_F',
  'BRAND_NAME_F',
  'DESCRIPTOR_F',
];

exports.status = [
  'DRUG_CODE',
  'CURRENT_STATUS_FLAG',
  'CLASS',
  'STATUS',
  'HISTORY_DATE',
  'STATUS_F',
  'LOT_NUMBER',
  'EXPIRATION_DATE',
];

exports.status = [
  'DRUG_CODE',
  'CURRENT_STATUS_FLAG',
  'CLASS',
  'STATUS',
  'HISTORY_DATE',
  'STATUS_F',
  'LOT_NUMBER',
  'EXPIRATION_DATE',
];

exports.form = [
  'DRUG_CODE',
  'PHARM_FORM_CODE',
  'PHARMACEUTICAL_FORM',
  'PHARMACEUTICAL_FORM_F',
];

exports.package = [
  'DRUG_CODE',
  'UPC',
  'PACKAGE_SIZE_UNIT',
  'PACKAGE_TYPE',
  'PACKAGE_SIZE',
  'PRODUCT_INFORMATION',
  'PACKAGE_SIZE_UNIT_F',
  'PACKAGE_TYPE_F',
];

exports.pharm = ['DRUG_CODE', 'PHARMACEUTICAL_STD'];

exports.route = [
  'DRUG_CODE',
  'ROUTE_OF_ADMINISTRATION_CODE',
  'ROUTE_OF_ADMINISTRATION',
  'ROUTE_OF_ADMINISTRATION_F',
];

exports.schedule = ['DRUG_CODE', 'SCHEDULE', 'SCHEDULE_F'];

exports.ther = [
  'DRUG_CODE',
  'TC_ATC_NUMBER',
  'TC_ATC',
  'TC_AHFS_NUMBER',
  'TC_AHFS',
  'TC_ATC_F',
  'TC_AHFS_F',
];

exports.vet = ['DRUG_CODE', 'VET_SPECIES', 'VET_SUB_SPECIES', 'VET_SPECIES_F'];
